[project]
name = "pokemon-api"
version = "0.1.0"
description = "A fun Pokemon API using PokeAPI"
readme = "README.md"
requires-python = ">=3.10,<=3.13"
dependencies = [
    "fastapi-mcp>=0.3.3",
    "fastapi[standard]>=0.115.12",
]
